"""W3C PROV-inspired provenance graph for tracking data lineage."""

import hashlib
import json
import os
import threading
from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Optional


class NodeType(Enum):
    ENTITY = "entity"
    ACTIVITY = "activity"
    AGENT = "agent"


class EdgeType(Enum):
    WAS_GENERATED_BY = "wasGeneratedBy"
    USED = "used"
    WAS_ASSOCIATED_WITH = "wasAssociatedWith"
    WAS_DERIVED_FROM = "wasDerivedFrom"


def content_id(content: str) -> str:
    """Generate a truncated SHA-256 content-addressed ID."""
    return hashlib.sha256(content.encode("utf-8")).hexdigest()[:16]


@dataclass
class Node:
    id: str
    node_type: str
    label: str
    content: str = ""
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class Edge:
    edge_type: str
    source: str
    target: str
    metadata: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)


class ProvenanceGraph:
    """Accumulates provenance nodes and edges and serializes to JSON."""

    def __init__(self, output_path: Optional[str] = None):
        self._nodes: dict[str, Node] = {}
        self._edges: list[Edge] = []
        self._lock = threading.Lock()
        self._output_path = output_path

    @property
    def output_path(self) -> Optional[str]:
        return self._output_path

    def add_entity(self, label: str, content: str = "", **metadata) -> str:
        """Add an Entity node. Returns its content-addressed ID."""
        nid = content_id(content) if content else content_id(label)
        node = Node(
            id=nid,
            node_type=NodeType.ENTITY.value,
            label=label,
            content=content,
            metadata=metadata,
        )
        with self._lock:
            self._nodes[nid] = node
        return nid

    def add_activity(self, label: str, content: str = "", **metadata) -> str:
        """Add an Activity node. Returns its content-addressed ID."""
        nid = content_id(content) if content else content_id(label)
        node = Node(
            id=nid,
            node_type=NodeType.ACTIVITY.value,
            label=label,
            content=content,
            metadata=metadata,
        )
        with self._lock:
            self._nodes[nid] = node
        return nid

    def add_agent(self, label: str, **metadata) -> str:
        """Add an Agent node. Returns its content-addressed ID."""
        nid = content_id(label)
        node = Node(
            id=nid,
            node_type=NodeType.AGENT.value,
            label=label,
            metadata=metadata,
        )
        with self._lock:
            self._nodes[nid] = node
        return nid

    def was_generated_by(self, entity_id: str, activity_id: str, **metadata):
        """Record that an entity was generated by an activity."""
        edge = Edge(
            edge_type=EdgeType.WAS_GENERATED_BY.value,
            source=entity_id,
            target=activity_id,
            metadata=metadata,
        )
        with self._lock:
            self._edges.append(edge)

    def used(self, activity_id: str, entity_id: str, **metadata):
        """Record that an activity used an entity."""
        edge = Edge(
            edge_type=EdgeType.USED.value,
            source=activity_id,
            target=entity_id,
            metadata=metadata,
        )
        with self._lock:
            self._edges.append(edge)

    def was_associated_with(self, activity_id: str, agent_id: str, **metadata):
        """Record that an activity was associated with an agent."""
        edge = Edge(
            edge_type=EdgeType.WAS_ASSOCIATED_WITH.value,
            source=activity_id,
            target=agent_id,
            metadata=metadata,
        )
        with self._lock:
            self._edges.append(edge)

    def was_derived_from(self, derived_id: str, source_id: str, **metadata):
        """Record that an entity was derived from another entity."""
        edge = Edge(
            edge_type=EdgeType.WAS_DERIVED_FROM.value,
            source=derived_id,
            target=source_id,
            metadata=metadata,
        )
        with self._lock:
            self._edges.append(edge)

    def get_node(self, node_id: str) -> Optional[Node]:
        with self._lock:
            return self._nodes.get(node_id)

    @property
    def nodes(self) -> dict[str, Node]:
        with self._lock:
            return dict(self._nodes)

    @property
    def edges(self) -> list[Edge]:
        with self._lock:
            return list(self._edges)

    def save(self, path: Optional[str] = None):
        """Serialize the graph to JSON."""
        target = path or self._output_path
        if not target:
            return
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with self._lock:
            data = {
                "nodes": {nid: n.to_dict() for nid, n in self._nodes.items()},
                "edges": [e.to_dict() for e in self._edges],
            }
        with open(target, "w") as f:
            json.dump(data, f, indent=2)

    def to_dict(self) -> dict:
        with self._lock:
            return {
                "nodes": {nid: n.to_dict() for nid, n in self._nodes.items()},
                "edges": [e.to_dict() for e in self._edges],
            }


_provenance_graph: Optional[ProvenanceGraph] = None
_provenance_lock = threading.Lock()


def get_provenance_graph(output_path: Optional[str] = None) -> ProvenanceGraph:
    """Module-level singleton accessor for the ProvenanceGraph."""
    global _provenance_graph
    with _provenance_lock:
        if _provenance_graph is None:
            _provenance_graph = ProvenanceGraph(output_path=output_path)
        return _provenance_graph


def reset_provenance_graph():
    """Reset the singleton (for testing)."""
    global _provenance_graph
    with _provenance_lock:
        _provenance_graph = None
